AddCSLuaFile("shared.lua")
include("shared.lua")
/*-----------------------------------------------
	*** Copyright (c) 2012-2025 by DrVrej, All rights reserved. ***
	No parts of this code or any of its contents may be reproduced, copied, modified or adapted, 
	without the prior written consent of the author, unless otherwise indicated for stand-alone materials.
-----------------------------------------------*/
ENT.Model = {"models/props_junk/popcan01a.mdl"}
ENT.EntitiesToSpawn = {
	{EntityName = "NPC1", SpawnPosition = {vForward=50, vRight=0, vUp=0}, Entities = {"npc_vj_cof_upper", "npc_vj_cof_taller", "npc_vj_cof_suicider", "npc_vj_cof_stranger", "npc_vj_cof_slowerstuck", "npc_vj_cof_slowerno", "npc_vj_cof_slower3", "npc_vj_cof_slower1", "npc_vj_cof_sewmo", "npc_vj_cof_sawrunner", "npc_vj_cof_sawer", "npc_vj_cof_sawcrazy", "npc_vj_cof_phsycho", "npc_vj_cof_mace", "npc_vj_cof_krypandenej", "npc_vj_cof_faster", "npc_vj_cof_faceless2", "npc_vj_cof_croucher", "npc_vj_cof_crazyrunner", "npc_vj_cof_crawler", "npc_vj_cof_citalopram", "npc_vj_cof_child", "npc_vj_cof_baby"}},
	{EntityName = "NPC2", SpawnPosition = {vForward=0, vRight=100, vUp=0}, Entities = {"npc_vj_cof_upper", "npc_vj_cof_taller", "npc_vj_cof_suicider", "npc_vj_cof_stranger", "npc_vj_cof_slowerstuck", "npc_vj_cof_slowerno", "npc_vj_cof_slower3", "npc_vj_cof_slower1", "npc_vj_cof_sewmo", "npc_vj_cof_sawrunner", "npc_vj_cof_sawer", "npc_vj_cof_sawcrazy", "npc_vj_cof_phsycho", "npc_vj_cof_mace", "npc_vj_cof_krypandenej", "npc_vj_cof_faster", "npc_vj_cof_faceless2", "npc_vj_cof_croucher", "npc_vj_cof_crazyrunner", "npc_vj_cof_crawler", "npc_vj_cof_citalopram", "npc_vj_cof_child", "npc_vj_cof_baby"}},
	{EntityName = "NPC3", SpawnPosition = {vForward=100, vRight=100, vUp=0}, Entities = {"npc_vj_cof_upper", "npc_vj_cof_taller", "npc_vj_cof_suicider", "npc_vj_cof_stranger", "npc_vj_cof_slowerstuck", "npc_vj_cof_slowerno", "npc_vj_cof_slower3", "npc_vj_cof_slower1", "npc_vj_cof_sewmo", "npc_vj_cof_sawrunner", "npc_vj_cof_sawer", "npc_vj_cof_sawcrazy", "npc_vj_cof_phsycho", "npc_vj_cof_mace", "npc_vj_cof_krypandenej", "npc_vj_cof_faster", "npc_vj_cof_faceless2", "npc_vj_cof_croucher", "npc_vj_cof_crazyrunner", "npc_vj_cof_crawler", "npc_vj_cof_citalopram", "npc_vj_cof_child", "npc_vj_cof_baby"}},
	{EntityName = "NPC4", SpawnPosition = {vForward=100, vRight=-100, vUp=0}, Entities = {"npc_vj_cof_upper", "npc_vj_cof_taller", "npc_vj_cof_suicider", "npc_vj_cof_stranger", "npc_vj_cof_slowerstuck", "npc_vj_cof_slowerno", "npc_vj_cof_slower3", "npc_vj_cof_slower1", "npc_vj_cof_sewmo", "npc_vj_cof_sawrunner", "npc_vj_cof_sawer", "npc_vj_cof_sawcrazy", "npc_vj_cof_phsycho", "npc_vj_cof_mace", "npc_vj_cof_krypandenej", "npc_vj_cof_faster", "npc_vj_cof_faceless2", "npc_vj_cof_croucher", "npc_vj_cof_crazyrunner", "npc_vj_cof_crawler", "npc_vj_cof_citalopram", "npc_vj_cof_child", "npc_vj_cof_baby"}},
	{EntityName = "NPC5", SpawnPosition = {vForward=0, vRight=-100, vUp=0}, Entities = {"npc_vj_cof_upper", "npc_vj_cof_taller", "npc_vj_cof_suicider", "npc_vj_cof_stranger", "npc_vj_cof_slowerstuck", "npc_vj_cof_slowerno", "npc_vj_cof_slower3", "npc_vj_cof_slower1", "npc_vj_cof_sewmo", "npc_vj_cof_sawrunner", "npc_vj_cof_sawer", "npc_vj_cof_sawcrazy", "npc_vj_cof_phsycho", "npc_vj_cof_mace", "npc_vj_cof_krypandenej", "npc_vj_cof_faster", "npc_vj_cof_faceless2", "npc_vj_cof_croucher", "npc_vj_cof_crazyrunner", "npc_vj_cof_crawler", "npc_vj_cof_citalopram", "npc_vj_cof_child", "npc_vj_cof_baby"}},
}
/*-----------------------------------------------
	*** Copyright (c) 2012-2025 by DrVrej, All rights reserved. ***
	No parts of this code or any of its contents may be reproduced, copied, modified or adapted, 
	without the prior written consent of the author, unless otherwise indicated for stand-alone materials.
-----------------------------------------------*/