-- DEPRECATED.
--
-- The ZScav meds SWEP base lived here in the first iteration (it set up
-- ZScavMeds.BaseSWEP and child SWEPs cloned it via table.Copy). That
-- pattern doesn't always register cleanly with GMod's weapons loader
-- because GMod runs SWEP files in a sandboxed environment where
-- reassigning the SWEP global doesn't always propagate to weapons.Register.
--
-- The base is now a normal Garry's Mod base SWEP at:
--   lua/weapons/weapon_zscav_med_base.lua
--
-- Child SWEPs inherit it the canonical way:
--   SWEP.Base = "weapon_zscav_med_base"
--
-- Nothing should include this file anymore. Safe to delete.
